# Generated by Django 3.1.3 on 2021-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210119_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksale',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booksale',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
